### ISSUE TITLE
Target Placeholders Rendering is absent in source code

### ISSUE THREAD

**Issue by zelwise** [martinrayenglish/PresentationTargets#1]
/sitecore/layout/Renderings/Presentation Targets/Presentation Targets Rendering inherit from
template: {2A3E91A0-7987-44B5-AB34-35C2D9DE83B9}
templatekey: Target Placeholders Rendering
but it absent in source project

**Comment by martinrayenglish** [comment]
Added the missing rendering template as well as a Sitecore package with all the necessary artifacts.  Let me know if you run into any other issues.

Thanks!
